### ISSUE TITLE
无法解析，一直处于解析中😀😀😀

### ISSUE THREAD

**Issue by yoel-du** [zhangzhichaolove/91porn-android#11]

**Comment by zhangzhichaolove** [comment]
也许未及时查看消息，看到后会及时回复。

**Comment by zhangzhichaolove** [comment]
经过你的反馈，我这边重新调试分析了，源站加密方式变更，请等待适配。

**Comment by zhangzhichaolove** [comment]
等待适配>

**Comment by zhangzhichaolove** [comment]
> 

等待适配。

**Comment by kangkangkangkkkk** [comment]
不知结果如何？

**Comment by zhangzhichaolove** [comment]
先处理工作内容，闲下来修复，应该就这两天。> 不知结果如何？

**Comment by ddrwin** [comment]
我以为是我网络问题呢，换了三个运营商网络都解析出不来，原来是数据源的问题。谢谢zhang修复，祝顺利！

**Comment by zhangzhichaolove** [comment]
已经修复，稍后发版，这个版本可能会有些许改动:
1.host地址改为自己配置。
2.另外视频播放加入缓存。

**Comment by zhangzhichaolove** [comment]
已发布修复。

**Comment by yoel-du** [comment]
有人试了吗好像还是一直解析中

**Comment by zhangzhichaolove** [comment]
难道发错包了？明天再看看。> 有人试了吗好像还是一直解析中

**Comment by zhangzhichaolove** [comment]
刚才我用同一个包试了，某些分类下获取数据异常，点了一个有数据的分类进行播放，能成功解析并播放，可能是我配置的地址不稳定，你们自行去找没有被墙的地址测试看看。

**Comment by a22124497** [comment]
解析不出来，闭幕式了多个地址，梯子或直接连的地址，不稳

**Comment by zhangzhichaolove** [comment]
已经找到原因:
1.源站会限制大陆IP访问（此问题使用app会进行伪装，主要原因是运营商拦截）。
2.经过测试，移动运营商会拦截请求，可以长按悬浮图标通过复制地址在浏览器打开测试。

使用运营商不会拦截的网址替换app地址，或使用电信联通网络。
