### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by yongdaimei** [zhangzhichaolove/91porn-android#2]
分类和官网不一样，能不能弄成官网那样的有最新啥的

**Comment by zhangzhichaolove** [comment]
最近手里没有root过的手机，不能抓app的包，目前分类是根据电脑浏览器解析的分类。

**Comment by yongdaimei** [comment]
@zhangzhichaolove 是我自己没注意，官网也没有最新这个分类，点高清就是按上传时间排序的

**Comment by zhangzhichaolove** [comment]
好的。
