### ISSUE TITLE
无法加载数据或者无法播放的请下载最新版本解决。

### ISSUE THREAD

**Issue by zhangzhichaolove** [zhangzhichaolove/91porn-android#3]

**Comment by yongdaimei** [comment]
好像播放不了了

**Comment by zhangzhichaolove** [comment]
也许未及时查看消息，看到后会及时回复。

**Comment by zhangzhichaolove** [comment]
是的，我今天晚上也发现了，等我修复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月12日(周日) 凌晨0:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangzhichaolove/91porn-android] 无法加载数据或者无法播放的请下载最新版本解决。 (#3)




 
好像播放不了了

**Comment by zhangzhichaolove** [comment]
## 下载新版本1.0.8已修复。

**Comment by yongdaimei** [comment]
> ## 下载新版本1.0.8已修复。

已更新，完美

**Comment by zhangzhichaolove** [comment]
已修复，请下载最新版本。
