### ISSUE TITLE
excellent app

### ISSUE THREAD

**Issue by HelpfulMrWang** [zhangzhichaolove/91porn-android#6]
视频详情页可以参考https://github.com/techGay/v9porn 加入up主历史作品
如果出个兼容电视的客户端那就更加perfect

**Comment by zhangzhichaolove** [comment]
不好意思，现在才看到，我分析了一下源站，发现每个用户跟踪进去基本都仅有单个视频，所以暂时觉得这个功能没多大必要，如果每个作者都有一个系列视频倒是可以加上这个功能。
另外电视客户端我觉得没必要吧。。。。谁还敢在家拿着电视看这些。。。。

**Comment by jw-star** [comment]
> 视频详情页可以参考https://github.com/techGay/v9porn 加入up主历史作品 如果出个兼容电视的客户端那就更加perfect

历史视频可以在 hao se 上看
