### ISSUE TITLE
播放速度，本地收藏，网页限制，作者其他视频

### ISSUE THREAD

**Issue by bai12123** [zhangzhichaolove/91porn-android#8]
大佬你好，app使用很nice，要是多几个功能就更完美了，以及有一个帮助请求帮忙,谢谢你

1.app暂时不支持倍速播放，希望可以加进去，官网是有的
2.遇到好看的视频希望可以本地一键收藏
3.虽然大多数作者可能只有一两个，但也是有相当一部分作者有很多视频，加入作者历史视频还是有必要的
4.大佬大佬，网页端破解播放数量限制，能请求你写个油猴脚本吗?目前还没有看到有这个脚本，当然愿不愿意都可以，这只是我个人的请求

ps：大佬需要捐赠吗？请你喝杯奶茶

**Comment by zhangzhichaolove** [comment]
#### 不需要捐赠哈，仅仅为练习个人技术而已。
你这次提这几点，其实都可以做的，但是目前我做了更好的解决方案，所以app这边没有怎么更新。
##### app目前问题：
1.数据从源站获取，解析过程很慢，播放也非常容易卡顿。
2.app目前只能在android设备使用，没有跨平台优势。
3.倍速，收藏等功能是可以做的。
#### web版本优势：
1.多端适配，跨平台优势。
2.B/S架构，用服务端及时更新数据，下载至本地，并实时转码，观看非常流畅，不卡顿。
3.功能易扩展，添加功能实时预览，更新方便。
### 目前最大的问题：
web端优势很多，且工程已经完成线上部署，但是由于数据存在本地，安全性堪忧，所以仅用来自己观看，虽然技术无罪，但是也不能刻意宣传，所以就不能开放出来使用了。
### 后续工作不忙的时候，我可以给app加上你说的这几项功能。

**Comment by zhangzhichaolove** [comment]
## 已增加：
1.增加本地收藏功能

**Comment by bai12123** [comment]
感谢
