### ISSUE TITLE
作者有做搜索功能的想法吗

### ISSUE THREAD

**Issue by ccoQQQ** [zhangzhichaolove/91porn-android#9]

**Comment by zhangzhichaolove** [comment]
也许未及时查看消息，看到后会及时回复。

**Comment by zhangzhichaolove** [comment]
目前官方搜索需要用户登录授权才行，但是登录会影响app模拟游客模式，导致无法进行无限观看，所以这个功能暂时有冲突。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月6日(周三) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhangzhichaolove/91porn-android] 作者有做搜索功能的想法吗 (Issue #9)

**Comment by zhangzhichaolove** [comment]
close.
